- name: Build image with infra.osbuild.builder
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3.12

  pre_tasks:
    - name: Ensure pip is installed for Python 3.12
      package:
        name: python3.12-pip
        state: present
      become: true

    - name: Ensure toml and tomli modules are installed
      pip:
        name:
          - toml
          - tomli
        executable: pip3.12
      become: true

  roles:
    - role: infra.osbuild.builder
      vars:
        # your role vars go here


ansible -m setup localhost | grep ansible_python_interpreter
python3.12 -m pip install tomli
or rpm package
python3-tomli
python3-toml

[buildhost]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3.12
validate import works
python3.12 -c "import toml; print(toml.__version__)"
