- name: reg host
  hosts: all
  become: true
  vars:
    rhc_auth:
      activation_keys:
        keys: [""]
    rhc_organization: ""
    rhc_enable_insights: false  # Ensure Insights is disabled
    rhc_repositories:
      - {name: "rhel-9-for-x86_64-baseos-rpms", state: enabled}
      - {name: "rhel-9-for-x86_64-appstream-rpms", state: enabled}
      - {name: "satellite-utils-6.16-for-rhel-9-x86_64-rpms", state: enabled}
      - {name: "satellite-maintenance-6.16-for-rhel-9-x86_64-rpms", state: enabled}
      - {name: "satellite-client-6-for-rhel-9-x86_64-rpms", state: enabled}
  roles:
    - redhat.rhel_system_roles.rhc
